DROP SCHEMA IF EXISTS MovieSystem;
CREATE SCHEMA MovieSystem;
USE MovieSystem;

CREATE TABLE GENDER (
	ID INT NOT NULL AUTO_INCREMENT, 
    DESCRIPTION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);
    
CREATE TABLE SCREENWRITER (
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(30) NOT NULL,
    AGE INT,
    FK_GENDER INT NOT NULL,
    FOREIGN KEY (FK_GENDER) REFERENCES GENDER(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE SCRIPT (
	ID INT NOT NULL AUTO_INCREMENT, 
    TIMES_MODIFIED INT,
    LAST_MODIFIED DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE COMPANY (
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(50),
    VALUE DOUBLE,
    PRIMARY KEY (ID)
);

CREATE TABLE MOVIE (
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL,
    DURATION_IN_MINUTES INT NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    CRITIC_REVIEW DOUBLE,
    FK_SCRIPT INT NOT NULL UNIQUE,
	FK_COMPANY INT NOT NULL,
	FOREIGN KEY (FK_SCRIPT) REFERENCES SCRIPT(ID),
	FOREIGN KEY (FK_COMPANY) REFERENCES COMPANY(ID),
    PRIMARY KEY (ID)
);
    
CREATE TABLE SCREENWRITER_MOVIE (
	FK_MOVIE INT NOT NULL, 
    FK_SCREENWRITER INT NOT NULL,
	FOREIGN KEY (FK_MOVIE) REFERENCES MOVIE(ID),
	FOREIGN KEY (FK_SCREENWRITER) REFERENCES SCREENWRITER(ID),
    PRIMARY KEY (FK_MOVIE, FK_SCREENWRITER)
);